### PR TITLE
Improve performance through various small fixes

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by franz1981** [comment]
This patch improve things, but the problem is still present, because of how the algorithm work i.e.
both producers/consumers perform type checks (explicit ones) to decide what to do next - which cause bringing the whole cache line of the class word in a shared state (including the subsequent task node's next field): this can slow down a concurrent winning thread which hasn't yet updated the next field, because it has to advertise through the cache coherency protocol the stale readers (of the same cache line).

'LinkedTransferQueue` advertize the content of the node by adding a `isData` field and using a single concrete type - which can contains a waiter `Thread` or not: probably moving to a flat hierarchy would benefit similarly our case as well.

**Comment by franz1981** [comment]
Another improvement which could be made (although not related to this)  is to hoist out of the tight loops the `unsharedTaskNodes` to be used in the tail/head accessors (including the compare and set ones!) 

see

```
   0.00%  │   0x00007f3ca6a6a3a2: mov    0x10(%r10),%r11d   ;*getfield this$0 {reexecute=0 rethrow=0 return_oop=0}
          │                                                 ; - org.jboss.threads.EnhancedQueueExecutor$ThreadBody::getOrAddNode@1 (line 1686)
          │                                                 ; - org.jboss.threads.EnhancedQueueExecutor$ThreadBody::run@49 (line 1596)
   0.05%  │   0x00007f3ca6a6a3a6: mov    0x48(%r11),%r10d   ; implicit exception: dispatches to 0x00007f3ca6a6b128
   0.01%  │   0x00007f3ca6a6a3aa: mov    0x90(%r10),%r10d
```
this is happening every time we need to read `getHead` ie:
1. it first read the `this$0` field which contains the executor reference within the `ThreadBody`class
2. it navigate to the `unsharedTaskNodes` field i.e. 0x48 === 72 
```
org.jboss.threads.EnhancedQueueExecutor object internals:
OFF  SZ                       TYPE DESCRIPTION                                  VALUE
  0   8                            (object header: mark)                        N/A
  8   4                            (object header: class)                       N/A
 12   4                      float EnhancedQueueExecutor.growthResistance       N/A
 16   8                       long EnhancedQueueExecutor.timeoutNanos           N/A
 24   4                        int EnhancedQueueExecutor.peakThreadCount        N/A
 28   4                        int EnhancedQueueExecutor.peakQueueSize          N/A
 32   4                        int EnhancedQueueExecutor.activeCount            N/A
 36   1                    boolean EnhancedQueueExecutor.queueLimited           N/A
 37   3                            (alignment/padding gap)                      
 40   4              ThreadFactory EnhancedQueueExecutor.threadFactory          N/A
 44   4                Set<Thread> EnhancedQueueExecutor.runningThreads         N/A
 48   4                 MXBeanImpl EnhancedQueueExecutor.mxBean                 N/A
 52   4                     Object EnhancedQueueExecutor.handle                 N/A
 56   4       AccessControlContext EnhancedQueueExecutor.acc                    N/A
 60   4          ContextHandler<?> EnhancedQueueExecutor.contextHandler         N/A
 64   4              SchedulerTask EnhancedQueueExecutor.schedulerTask          N/A
 68   4                     Thread EnhancedQueueExecutor.schedulerThread        N/A
 72   4                 TaskNode[] EnhancedQueueExecutor.unsharedTaskNodes      N/A  <----------------------- THIS ONE!
 76   4                     long[] EnhancedQueueExecutor.unsharedLongs          N/A  
 80   4                     Waiter EnhancedQueueExecutor.terminationWaiters     N/A
 84   4                   Executor EnhancedQueueExecutor.handoffExecutor        N/A
 88   4   UncaughtExceptionHandler EnhancedQueueExecutor.exceptionHandler       N/A
 92   4                   Runnable EnhancedQueueExecutor.terminationTask        N/A
 96   4                  LongAdder EnhancedQueueExecutor.submittedTaskCounter   N/A
100   4                  LongAdder EnhancedQueueExecutor.completedTaskCounter   N/A
104   4                  LongAdder EnhancedQueueExecutor.rejectedTaskCounter    N/A
108   4                  LongAdder EnhancedQueueExecutor.spinMisses             N/A
Instance size: 112 bytes
Space losses: 3 bytes internal + 0 bytes external = 3 bytes total
```
3. it reads the head element at offset `0x90` in the array - which is indeed 144 (16 array offset + 128 padding)

Said that, it will just make the tight loops `tryExecute` and `getOrAddNode` faster - which will "looks like" further hurting performance

**Comment by franz1981** [comment]
Another interesting difference between LTQ and jboss-threads is that:
- consumer threads for LTQ, while "matched" they likely succeed to execute a task 
- consumer threads for LTQ try hard to not go to sleep/park immediately - but used some form of spinning/yielding before parking
- consumer threads for jboss-threads, while unparked, still race with others to acquire a task to execute (which makes it less fair)

This last point means that we maybe can observe as more costly some of the code paths of the consumer - but in reality they cost more because there are more loops/spin before the consumer win

**Comment by dmlloyd** [comment]
Did any of these changes help?

**Comment by franz1981** [comment]
Today didn't had my Ryzen beast around so couldn't do it. Next week will give it another round; in general, reducing the number of type checks will improve for sure, due to the cache coherency thing I have mentioned.
I have the feeling (to be proved) that, on the consumer, removing the read of next field to verify that's not pointing to itself, despite it seems a good idea (and is correct) is better instead to avoid it and just let it fail the compare and set later on (it should fail), to avoid disturbing the writing activity of the thread which won the race to consume it.

**Comment by dmlloyd** [comment]
The new changes remove most of the pointer-chasing so I expect the new results to be quite different (though maybe/maybe not better).

**Comment by franz1981** [comment]
@dmlloyd 

I'm re running the tests to be sure, but on my 32 Ryzen 7950X I'm getting
```

Benchmark                           (burstSize)  (cores)  (executorThreads)                (factory)  (spinWaitCompletion)  Mode  Cnt    Score     Error  Units
ExecutorBenchmarks.benchmarkSubmit          100        0                8,8  ENHANCED_QUEUE_EXECUTOR                 false  avgt    8  379.862 ± 287.679  us/op
```
Before these changes and 
```
Benchmark                           (burstSize)  (cores)  (executorThreads)                (factory)  (spinWaitCompletion)  Mode  Cnt    Score    Error  Units
ExecutorBenchmarks.benchmarkSubmit          100        0                8,8  ENHANCED_QUEUE_EXECUTOR                 false  avgt    8  167.910 ± 18.469  us/op
```

**Review by franz1981 — APPROVED** [review]
LGTM, well done!

**Comment by franz1981** [comment]
For completeness @dmlloyd 
```....[Hottest Region 1]..............................................................................
c2, level 4, org.jboss.threads.EnhancedQueueExecutor::runThreadBody, version 2, compile id 1615 

             0x00007f2a30685635:   je     0x00007f2a30685645
             0x00007f2a30685637:   cmpb   $0x0,0x40(%r15)
             0x00007f2a3068563c:   jne    0x00007f2a30686218
             0x00007f2a30685642:   mov    %r12d,(%r14)                 ;*invokevirtual compareAndSetReference {reexecute=0 rethrow=0 return_oop=0}
                                                                       ; - sun.misc.Unsafe::compareAndSwapObject@9 (line 906)
                                                                       ; - org.jboss.threads.EnhancedQueueExecutor::compareAndSetHead@9 (line 2035)
                                                                       ; - org.jboss.threads.EnhancedQueueExecutor::runThreadBody@446 (line 1691)
          ↗  0x00007f2a30685645:   mov    0x458(%r15),%r10             ; ImmutableOopMap {[8]=Oop [16]=Oop [0]=Derived_oop_[16] [24]=NarrowOop [40]=Oop [48]=Oop [96]=Oop }
          │                                                            ;*ifeq {reexecute=1 rethrow=0 return_oop=0}
          │                                                            ; - (reexecute) org.jboss.threads.EnhancedQueueExecutor::runThreadBody@526 (line 1710)
   0.01%  │  0x00007f2a3068564c:   test   %eax,(%r10)                  ;*aload_0 {reexecute=0 rethrow=0 return_oop=0}
          │                                                            ; - org.jboss.threads.EnhancedQueueExecutor::runThreadBody@21 (line 1608)
          │                                                            ;   {poll}
   0.00%  │  0x00007f2a3068564f:   mov    0x30(%rsp),%r10
   0.00%  │  0x00007f2a30685654:   test   %r10,%r10
          │  0x00007f2a30685657:   je     0x00007f2a30686531
          │  0x00007f2a3068565d:   mov    (%rsp),%r10
          │  0x00007f2a30685661:   mov    (%r10),%ebx
  39.35%  │  0x00007f2a30685664:   mov    %ebx,%r14d                   ;*invokevirtual getReferenceVolatile {reexecute=0 rethrow=0 return_oop=0}
          │                                                            ; - sun.misc.Unsafe::getObjectVolatile@5 (line 947)
          │                                                            ; - org.jboss.threads.EnhancedQueueExecutor::getHead@7 (line 2026)
          │                                                            ; - org.jboss.threads.EnhancedQueueExecutor::runThreadBody@23 (line 1608)
   0.11%  │  0x00007f2a30685667:   test   %ebx,%ebx
          │  0x00007f2a30685669:   je     0x00007f2a30686544           ;*invokevirtual getNext {reexecute=0 rethrow=0 return_oop=0}
          │                                                            ; - org.jboss.threads.EnhancedQueueExecutor::runThreadBody@30 (line 1609)
          │  0x00007f2a3068566f:   mov    %rbx,%r10                    ;*invokevirtual getReferenceVolatile {reexecute=0 rethrow=0 return_oop=0}
          │                                                            ; - sun.misc.Unsafe::getObjectVolatile@5 (line 947)
          │                                                            ; - org.jboss.threads.EnhancedQueueExecutor::getHead@7 (line 2026)
          │                                                            ; - org.jboss.threads.EnhancedQueueExecutor::runThreadBody@23 (line 1608)
   0.02%  │  0x00007f2a30685672:   mov    %r10,0x20(%rsp)
   0.00%  │  0x00007f2a30685677:   lea    0xc(%rbx),%rbx
          │  0x00007f2a3068567b:   mov    (%rbx),%r10d                 ;*getfield next {reexecute=0 rethrow=0 return_oop=0}
          │                                                            ; - org.jboss.threads.EnhancedQueueExecutor$QNode::getNext@1 (line 2312)
          │                                                            ; - org.jboss.threads.EnhancedQueueExecutor::runThreadBody@30 (line 1609)
   5.76%  │  0x00007f2a3068567e:   cmp    %r14d,%r10d
   0.02%  ╰  0x00007f2a30685681:   je     0x00007f2a30685645           ;*if_acmpeq {reexecute=0 rethrow=0 return_oop=0}
                                                                       ; - org.jboss.threads.EnhancedQueueExecutor::runThreadBody@39 (line 1612)
             0x00007f2a30685683:   test   %r10d,%r10d
   0.03%     0x00007f2a30685686:   je     0x00007f2a30685ccb           ;*ifnull {reexecute=0 rethrow=0 return_oop=0}
                                                                       ; - org.jboss.threads.EnhancedQueueExecutor::runThreadBody@44 (line 1613)
             0x00007f2a3068568c:   mov    0x8(%r10),%r8d               ;*instanceof {reexecute=0 rethrow=0 return_oop=0}
                                                                       ; - org.jboss.threads.EnhancedQueueExecutor::runThreadBody@427 (line 1690)
   4.24%     0x00007f2a30685690:   mov    %r10,%r11                    ;*getfield next {reexecute=0 rethrow=0 return_oop=0}
                                                                       ; - org.jboss.threads.EnhancedQueueExecutor$QNode::getNext@1 (line 2312)
                                                                       ; - org.jboss.threads.EnhancedQueueExecutor::runThreadBody@30 (line 1609)
   0.06%     0x00007f2a30685693:   mov    %r11,0x38(%rsp)
   0.01%     0x00007f2a30685698:   cmp    $0x1089300,%r8d              ;   {metadata(&apos;org/jboss/threads/EnhancedQueueExecutor$PoolThreadNode&apos;)}
   0.03%     0x00007f2a3068569f:   jne    0x00007f2a30685930           ;*aload_3 {reexecute=0 rethrow=0 return_oop=0}
                                                                       ; - org.jboss.threads.EnhancedQueueExecutor::runThreadBody@55 (line 1614)
             0x00007f2a306856a5:   mov    0x60(%rsp),%r10
   0.00%     0x00007f2a306856aa:   test   %r10,%r10
   0.00%     0x00007f2a306856ad:   je     0x00007f2a30686558           ;*invokevirtual setNextRelaxed {reexecute=0 rethrow=0 return_oop=0}
                                                                       ; - org.jboss.threads.EnhancedQueueExecutor::runThreadBody@58 (line 1614)
             0x00007f2a306856b3:   mov    0x60(%rsp),%r14
             0x00007f2a306856b8:   add    $0xc,%r14                    ;*invokevirtual compareAndSetReference {reexecute=0 rethrow=0 return_oop=0}
                                                                       ; - sun.misc.Unsafe::compareAndSwapObject@9 (line 906)
                                                                       ; - org.jboss.threads.EnhancedQueueExecutor::compareAndSetHead@9 (line 2035)
                                                                       ; - org.jboss.threads.EnhancedQueueExecutor::runThreadBody@446 (line 1691)
             0x00007f2a306856bc:   cmpb   $0x0,0x40(%r15)
   0.00%     0x00007f2a306856c1:   jne    0x00007f2a30685df4
             0x00007f2a306856c7:   mov    0x38(%rsp),%r10
             0x00007f2a306856cc:   mov    %r10,%rbp
             0x00007f2a306856cf:   mov    %ebp,(%r14)
             0x00007f2a306856d2:   mov    %r14,%r10                    ;*invokevirtual putReference {reexecute=0 rethrow=0 return_oop=0}
                                                                       ; - sun.misc.Unsafe::putObject@7 (line 213)
                                                                       ; - org.jboss.threads.EnhancedQueueExecutor$QNode::setNextRelaxed@8 (line 2320)
                                                                       ; - org.jboss.threads.EnhancedQueueExecutor::runThreadBody@58 (line 1614)
             0x00007f2a306856d5:   mov    0x60(%rsp),%r11
             0x00007f2a306856da:   mov    %r11,%r13                    ;*invokevirtual compareAndSetReference {reexecute=0 rethrow=0 return_oop=0}
                                                                       ; - sun.misc.Unsafe::compareAndSwapObject@9 (line 906)
....................................................................................................
  49.65%  <total for region 1>

```
This is showing that:
1.  `getHead`  is super hot - as expected - both because is happening frequently and/or because it's highly contented
i.e.
```
          │  0x00007f2a3068565d:   mov    (%rsp),%r10        <-- this is reading the absolute address of the head element out of the top of the stack, as unsharedTaskNodes and RuntimeFields.headOffset are constant
          │  0x00007f2a30685661:   mov    (%r10),%ebx       <-- this load the head element out of the executor
  39.35%  │  0x00007f2a30685664:   mov    %ebx,%r14d 
  ```
2. `getfield next` and reading the class word (to check the node type) are not super costly, but still costy i.e. `5.76%` and `4.24% `, respectively 

For the latter point, it is not yet fully clear if the `next` field and the class word are costly because of a data dependency
i.e.

read head field -> navigate head to read next -> navigate head.next to read its type

and/or because of some form of sharing

**Pull request merged**
