### PR TITLE
[JBTHR-55] Thread exit hooks

### PR DESCRIPTION
**Pull request by msfm**
Backport https://issues.redhat.com/browse/JBTHR-55 to 2.3 branch
Upstream PR: #38

### CODE REVIEW

**Comment by dmlloyd** [comment]
Normally we don't backport features to minor branches (otherwise the minor branch eventually becomes a more complex and harder to maintain copy of a newer branch).  Can we use a newer version instead?

**Comment by wolfc** [comment]
WildFly (Core) depends on the API which was stripped down through https://issues.redhat.com/browse/JBTHR-62. It is not trivial to refactor it (let alone EAP 7.3).

**Comment by dmlloyd** [comment]
@wolfc the stripping down occurred in 3.x, not 2.x.  I'm talking about starting a new 2.x branch (2.4.x) for this purpose, which includes all the 2.3 changes plus any additional features that need adding to get past the current problem.

**Comment by wolfc** [comment]
If 2.4 becomes a simple drop-in upgrade then I see no problem going down that route.

**Comment by msfm** [comment]
As using 2.4 looks better than backporting to 2.3, I'm closing this PR

**Pull request closed without merging**
